#!/bin/bash

set -e

namespace=$1
sa_name=$2

server=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')

# the name of the secret containing the service account token
secret_name=$(kubectl -n $namespace get sa $sa_name -o jsonpath='{.secrets[0].name}')

ca=$(kubectl -n $namespace get secret $secret_name -o jsonpath='{.data.ca\.crt}')
token=$(kubectl -n $namespace get secret $secret_name -o jsonpath='{.data.token}' | base64 --decode)

echo "apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    certificate-authority-data: ${ca}
    server: ${server}
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: ${namespace}
    user: ${sa_name}
current-context: default-context
users:
- name: ${sa_name}
  user:
    token: ${token}"
